login/urls.py
from django.urls import path
from .views import signup, MyLogoutView, LoginView

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('litreviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.conf import settings
from login.models import CustomUser
import os
from django.db import models
from django.db.models import Q

def book_image_path(instance, filename):
    # Obtenez le nom du fichier d'origine
    original_filename = filename

    # Obtenez le titre du livre de l'instance
    book_title = instance.book_title

    # Générez le nouveau nom de fichier en utilisant le titre du livre et l'extension d'origine
    new_filename = f"{book_title}.{original_filename.split('.')[-1]}"

    # Retournez le chemin complet du fichier
    return os.path.join('book_images', new_filename)

class BookReviewTicket(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='review_tickets')
    date = models.DateTimeField(auto_now_add=True)
    book_title = models.CharField(max_length=255)
    book_author = models.CharField(max_length=255)
    request_text = models.TextField()
    book_image = models.ImageField(upload_to=book_image_path)


    def __str__(self):
        return self.book_title

class BookReview(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    text = models.TextField()
    ticket = models.ForeignKey(BookReviewTicket, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='following')
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='followers')

    class Meta:
        unique_together = ('user', 'followed_user', )

    def __str__(self):
        return f"{self.user.username} follows {self.followed_user.username}"


class UserReviewsAndTicketsQuerySet(models.QuerySet):
    def for_user(self, user):
        return self.filter(Q(author=user) | Q(user=user))


class UserReviewsAndTicketsManager(models.Manager):
    def get_queryset(self):
        return UserReviewsAndTicketsQuerySet(self.model, using=self._db)

    def for_user(self, user):
        return self.get_queryset().for_user(user)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LITRevu</title>
    <!-- Ajoutez vos liens CSS et autres méta-informations ici -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

</head>
<body>
    <!-- Barre de navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <!-- Logo et titre centré et plus grand -->
            <a class="navbar-brand text-center text-white" href="{% url 'home' %}">LITRevu</a>
            <!-- Liens à droite -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'user_reviews_tickets' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'manage_followers' %}">Abonnements</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'combined_list' %}">Flux</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <!-- Le contenu de la page va ici -->
        {% block content %}
        {% endblock %}
    </div>

    <!-- Ajoutez vos scripts JS ou autres éléments ici -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/book_review_detail.html
<!-- book_review_detail.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>Détails de la Critique</h1>

  <h2>{{ review.title }}</h2>
  <p>Date de Création de la review : {{ review.date }}</p>
  <p>Auteur de la Critique : {{ review.author }}</p>
  <p>Évaluation : {{ review.rating }}/5</p>
  <p>Commentaire : {{ review.text }}</p>

  <h2>Informations sur le Ticket</h2>
  <p>Titre du Ticket : {{ ticket.book_title }}</p>
  <p>Auteur du Ticket : {{ ticket.user }}</p>
  <p>Date de Création du Ticket : {{ ticket.date }}</p>
  <p>Description du Ticket : {{ ticket.text }}</p>
    <img src="{{ ticket.book_image.url }}" alt="{{ ticket.book_title }}">

  <a href="{% url 'ticket_list' %}">Retour à la Liste des Tickets</a>
{% endblock %}

templates/book_review_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Liste des Critiques de Livres</h1>
  <ul>
    {% for review in reviews %}
      <li><a href="{% url 'book_review_detail' review.id %}">{{ review.title }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url 'create_book_review' %}">Ajouter une Critique de Livre</a>
{% endblock %}

templates/combined_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="bg-primary p-3 rounded-top">
                <h1 class="text-center text-white mb-4">Flux des tickets et reviews</h1>
            </div>

            <div class="d-flex justify-content-between mt-4">
                <div class="container text-center mb-0">
                    <a href="{% url 'create_ticket' %}" class="btn btn-primary">Ecrire un ticket</a>
                </div>

                <div class="container text-center mb-0">
                    <a href="{% url 'create_book_review' %}" class="btn btn-primary">Ecrire une critique</a>
                </div>
            </div>

            <ul class="list-group mt-4">
                {% for item in combined_list %}
                    {% if item.ticket %}
                        <li class="list-group-item border border-3 mb-3 bg-light">
                            <div class="list-group-item border-2">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <p> {% if item.user.username %}{{ item.user.username }}{% else %}{{ item.author }}{% endif %} a écrit la critique</p>
                                    </div>
                                    <div>
                                        <p>Date: {{ item.date }}</p>
                                    </div>
                                </div>
                                <div class="d-flex">
    <h2><strong>{{ item.title }}</strong></h2>
    <span class="star-rating">
        {% for _ in "x"|ljust:item.rating %}
            <i class="fas fa-star"></i>
        {% endfor %}
    </span>
</div>

                                <div class="border rounded bg-light p-3">
                                    <p>{{ item.text }}</p>
                                </div>

                            </div>
                            <ul class="list-group mt-4">
                                <li class="list-group-item border border-2 mb-3">
                                    <div class="d-flex justify-content-between">
                                        <div class="left-content">
                                            <p class="mb-0">{% if item.ticket.user.username %}{{ item.ticket.user.username }}{% else %}{{ item.author }}{% endif %} a demandé une review</p>
                                        </div>
                                        <div class="right-content">
                                            <p class="mb-0">Date: {{ item.ticket.date }}</p>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between">
                                        <div class="left-content">
                                            <p>{{ item.ticket.book_title }} - {{ item.ticket.book_author }}</p>
                                        </div>
                                        <div class="right-content">
                                            <!-- Laissez cet espace vide pour aligner correctement les éléments -->
                                        </div>
                                    </div>
                                    <div class="border rounded bg-light p-3">
                                        <p>{{ item.ticket.text }}</p>
                                    </div>
                                    <div class="text-center mt-3">
                                        <img src="{{ item.ticket.book_image.url }}" alt="Book Image" class="img-fluid" style="max-width: 150px;">
                                    </div>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="list-group-item border border-4 mb-3">
                            <div>
                                <p>{% if item.user.username %}{{ item.user.username }}{% else %}{{ item.author }}{% endif %} a demandé une review</p>
                                <p>Date: {{ item.date }}</p>
                                <p>{{ item.book_title }} - {{ item.book_author }}</p>
                                <div class="border rounded bg-light p-3">
                                    <p>{{ item.text }}</p>
                                </div>
                                <span class="star-rating">
    {% if item.star_rating %}
        {% for _ in "x"|ljust:item.star_rating %}
            <i class="fas fa-star"></i>
        {% endfor %}
    {% endif %}
</span>

                                {% if item.book_image %}
                                    <div class="text-center mt-3">
                                        <img src="{{ item.book_image.url }}" alt="Book Image" class="img-fluid" style="max-width: 150px;">
                                    </div>
                                {% endif %}
                                {% if item.user and not item.bookreview_set.all %}
                                <a href="{% url 'response_review' item.id %}" class="btn btn-primary">Répondre</a>
                                {% endif %}
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/create_book_review.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="bg-primary p-3 rounded">
                    <h1 class="text-center text-white mb-4">Créer une Nouvelle Critique de Livre</h1>
                </div>

                <div class="card mt-4 border border-primary rounded">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Formulaire de Ticket -->
                            {% if ticket_form %}
                                <div class="form-group">
                                    {{ ticket_form.as_p|safe }}
                                </div>
                            {% endif %}
                            <div class="form-group">
                                {{ form.as_p|safe }}
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Soumettre</button>
                        </form>
                    </div>
                </div>

                <div class="mt-4">
                    <a href="{% url 'home' %}" class="btn btn-secondary btn-block rounded">Retour</a>
                </div>
            </div>
        </div>
    </div>

    <style>
        /* CSS personnalisé pour le style de la page */
        .card {
            border: none;
        }
    </style>
{% endblock %}

templates/create_ticket.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="bg-primary p-3 rounded">
                    <h1 class="text-center text-white mb-4">Créer un Nouveau Ticket</h1>
                </div>

                <div class="card mt-4 border border-primary rounded">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Créer le Ticket</button>
                        </form>
                    </div>
                </div>

                <div class="mt-4">
                    <a href="{% url 'combined_list' %}" class="btn btn-secondary btn-block rounded">Retour</a>
                </div>

                {% if messages %}
                    <ul class="messages mt-4">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <style>
        /* CSS personnalisé pour le style de la page */
        .card {
            border: none;
        }
    </style>
{% endblock %}

templates/manage_followers.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="bg-primary p-3 rounded-top">
                    <h1 class="text-center text-white mb-4">Gérer les Abonnements</h1>
                </div>

                <div class="card mt-4 border border-primary">
                    <div class="card-body">
                        <h2>Suivre un nouvel utilisateur :</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username_to_follow">Nom d'utilisateur à suivre :</label>
                                <input type="text" name="username_to_follow" class="form-control" required>
                            </div>
                            <div class="d-flex justify-content-between mt-3">
                                <button type="submit" class="btn btn-primary">Suivre</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="card mt-4 border border-primary">
                    <div class="card-body">
                        <h2>Utilisateurs que vous suivez :</h2>
                        <ul class="list-group">
                            {% for user_follows in following %}
                                <li class="list-group-item">{{ user_follows.followed_user.username }}</li>
                            {% empty %}
                                <p>Vous ne suivez personne pour le moment.</p>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="card mt-4 border border-primary">
                    <div class="card-body">
                        <h2>Personnes qui vous suivent :</h2>
                        <ul class="list-group">
                            {% for user_follows in followers %}
                                <li class="list-group-item">{{ user_follows.user.username }}</li>
                            {% empty %}
                                <p>Personne ne vous suit pour le moment.</p>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="mt-4">
                    <a href="{% url 'home' %}" class="btn btn-secondary btn-block">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    /* CSS personnalisé pour le style de la page */
    .card {
        border: solid 1px black;
        border-radius: 0.25rem;
    }
    .rounded-top {
        border-top-left-radius: 0.25rem;
        border-top-right-radius: 0.25rem;
    }
</style>
{% endblock %}

templates/modify_review.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="bg-primary p-3 rounded-top">
                <h1 class="text-center text-white mb-4">Modify Review</h1>
            </div>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </form>

            <a href="{% url 'combined_list' %}" class="btn btn-secondary mt-3">Cancel</a>
        </div>
    </div>
</div>
{% endblock %}

templates/modify_ticket.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="bg-primary p-3 rounded-top">
                <h1 class="text-center text-white mb-4">Modify Ticket</h1>
            </div>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="teximg-fluid">
                                        <img src="{{ ticket.book_image.url }}" alt="Book Image" class="img-fluid" style="max-width: 150px;">
                                </div>
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </form>

            <a href="{% url 'combined_list' %}" class="btn btn-secondary mt-3">Cancel</a>
        </div>
    </div>
</div>
{% endblock %}

templates/response_review.html
{% extends 'ticket_detail.html' %}

{% block content %}
  {{ block.super }}

  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="bg-primary p-3 rounded-top">
          <h1 class="text-center text-white mb-4">Répondre avec une Critique</h1>
        </div>

        <div class="my-4"> <!-- Ajout de marge autour du contenu -->
          <!-- Afficher les messages flash ici -->
          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}

          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="title">Titre :</label>
              <input type="text" id="title" name="title" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="rating">Note :</label>
              <select id="rating" name="rating" class="form-control" required>

                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
            <div class="form-group">
              <label for="text">Commentaire :</label>
              <textarea id="text" name="text" class="form-control" rows="4" required></textarea>
            </div>
            <div class="d-flex justify-content-between align-items-center my-4"> <!-- Ajout de la marge autour des boutons -->
              <button type="submit" class="btn btn-primary">Soumettre la Critique</button>
              <a href="{% url 'home' %}" class="btn btn-primary">Retour à l'Accueil</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% if review %}
    <div class="container mt-4">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <!-- Afficher la critique ici -->
          <div class="bg-secondary p-3 rounded-top">
            <h1 class="text-center text-white mb-4">Critique</h1>
          </div>
          <div class="bg-light p-3 rounded-bottom">
            <h2>Titre de la Critique : {{ review.title }}</h2>
            <p>Note : {{ review.rating }}</p>
            <p>Commentaire : {{ review.text }}</p>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
</div>
{% endblock %}

templates/ticket_confirmation.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="bg-primary p-3 rounded-top">
                <h1 class="text-center text-white mb-4">C'est validé !</h1>
            </div>

            <div class="bg-light p-4">
                <p>Votre saisie a bien été sauvegardée.</p>
                <!-- You can provide additional details or links here if needed -->
                <div class="text-center mt-4">
                    <a href="{% url 'home' %}" class="btn btn-primary">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/ticket_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="ticket-details bg-light p-4">
          <h1 class="mb-3">Détail du Ticket</h1>
          <h2>{{ ticket.title }}</h2>
          <p>Auteur du Ticket : {{ ticket.user }}</p>
          <p>Date et Heure de Création : {{ ticket.date }}</p>
          <p>Livre : {{ ticket.book_title }} par {{ ticket.book_author }}</p>
          <p>Description du Ticket : {{ ticket.text }}</p>
          <img src="{{ ticket.book_image.url }}" alt="{{ ticket.book_title }}" class="img-fluid mb-3 custom-img-class">

          <div class="d-flex justify-content-between">
            <!-- Vos autres éléments ici -->
          </div>
        </div>
      </div>
    </div>
  </div>

  <style>
    .custom-img-class {
      max-width: 150px;
    }

    /* Ajoutez ici d'autres règles CSS personnalisées si nécessaire */
  </style>
{% endblock %}

templates/ticket_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Liste des Tickets</h1>
  <ul>
    {% for ticket in tickets %}
      <li><a href="{% url 'ticket_detail' ticket.id %}">{{ ticket.title }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url 'create_ticket' %}">Créer un Nouveau Ticket</a>
{% endblock %}

templates/user_reviews_tickets.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="bg-primary p-3 rounded-top">
                <h1 class="text-center text-white mb-4">Your Reviews and Tickets</h1>
            </div>

            <ul class="list-group mt-4">
                {# Boucle à travers les critiques de l'utilisateur #}
                {% for review in user_reviews %}
                    <li class="list-group-item border border-3">
                        <div>
                            <h2><strong>{{ review.title }}</strong></h2>
                            <p>Date: {{ review.date }}</p>
                            <div class="border rounded bg-light p-3">
                                <p>{{ review.text }}</p>
                                <p>Posted by: {{ review.author.username }}</p>
                            </div>
                            <div class="text-center mt-3">
                                <a href="{% url 'modify_review' review.id %}" class="btn btn-primary">Modify</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}

                {# Boucle à travers les tickets de l'utilisateur #}
                {% for ticket in user_tickets %}
                    <li class="list-group-item border border-3">
                        <div>
                            <h2><strong>{{ ticket.book_title }}</strong></h2>
                            <p>Date: {{ ticket.date }}</p>
                            <div class="border rounded bg-light p-3">
                                <p>{{ ticket.text }}</p>
                                <p>Posted by: {{ ticket.user.username }}</p>
                                <div class="teximg-fluid">
                                        <img src="{{ ticket.book_image.url }}" alt="Book Image" class="img-fluid" style="max-width: 150px;">
                                </div>
                            </div>
                            <div class="text-center mt-3">
                                <a href="{% url 'modify_ticket' ticket.id %}" class="btn btn-primary">Modify</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}